### ISSUE TITLE
Extra ; around line rdcp.c:611

### ISSUE THREAD

**Issue by razeh** [roidayan/rdcp#6]
There is an extra semicolon around line 611 in rdcp.c:
`static void rdcp_free_buffers(struct rdcp_cb *cb)
{
        int i;

        VERBOSE_LOG(3, "rdcp_free_buffers called on cb %p\n", cb);
        if (cb->start_buf);   //  THIS SEMICOLON DOESN'T MATCH THE INDENTATION
                free(cb->start_buf);
        if (cb->rdma_mr)
`

**Comment by roidayan** [comment]
thanks
