### ISSUE TITLE
No error code returned on the client when copying non-existent files

### ISSUE THREAD

**Issue by razeh** [roidayan/rdcp#9]
If you copy a file that doesn't exist, the following sequence happens:
    cm_thread starts
    the client connects to the server
    rdcp_run_client runs, fails, disconnects and sleeps(1)
    cm_thread exits with a return status of 0

From a scripting point of view it makes it a bit more difficult to tell if things went wrong.

**Comment by roidayan** [comment]
tested and got exit code 255 actually.
anyway id small refactor (can be better) to get correct exit code 9 from open()

EBADF 9 Bad file descriptor

**Comment by roidayan** [comment]
thanks
